# Generated by Django 4.2.2 on 2023-06-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('rows', models.PositiveIntegerField()),
                ('seats_per_row', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
