# Generated by Django 4.2.2 on 2023-06-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='slug',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
