# Generated by Django 4.2.2 on 2023-06-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_hall_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
