# Generated by Django 4.2.2 on 2023-07-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_alter_hall_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='temp_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
