# Generated by Django 4.2.2 on 2023-07-15 10:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_hall_temp_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hall',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
