# Generated by Django 4.2.2 on 2023-07-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0006_remove_hall_image_url_hall_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='temp_img',
        ),
    ]
