# Generated by Django 4.2.2 on 2023-06-25 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projection', '0006_alter_projection_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tickets', models.PositiveIntegerField(blank=True, null=True)),
                ('type_of_tickets', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('reserved_seats', models.TextField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('projection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projection.projection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
