# Generated by Django 4.2.2 on 2023-06-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0006_alter_projection_date'),
        ('reservation', '0002_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='projection',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='projection.projection'),
            preserve_default=False,
        ),
    ]
