# Generated by Django 4.2.2 on 2023-06-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0002_hall_slug'),
        ('movies', '0004_movie_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
