# Generated by Django 4.2.2 on 2023-06-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projection',
            old_name='hall_id',
            new_name='hall',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
