# Generated by Django 4.2.2 on 2023-06-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0003_alter_projection_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_n', models.CharField()),
                ('seat_n', models.CharField()),
                ('is_taken', models.BooleanField(default=False)),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projection.projection')),
            ],
        ),
    ]
