# Generated by Django 4.2.2 on 2023-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0004_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
