# Generated by Django 4.2.2 on 2023-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0005_alter_projection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='date',
            field=models.DateField(default="2023-06-25"),
            preserve_default=False,
        ),
    ]
