# Generated by Django 4.2.2 on 2023-07-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_movie_image'),
        ('projection', '0006_alter_projection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='movie',
        ),
        migrations.AddField(
            model_name='projection',
            name='movie',
            field=models.ManyToManyField(to='movies.movie'),
        ),
    ]
