# Generated by Django 4.2.2 on 2023-07-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_movie_image'),
        ('projection', '0007_remove_projection_movie_projection_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='movie',
        ),
        migrations.AddField(
            model_name='projection',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
    ]
