# Generated by Django 4.2.2 on 2023-06-20 07:04

import CTRS_course_project.user_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_appuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), CTRS_course_project.user_app.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), CTRS_course_project.user_app.validators.validate_only_letters]),
        ),
    ]
