# Generated by Django 4.2.2 on 2023-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.TextField(),
        ),
    ]
