# Generated by Django 4.2.2 on 2023-06-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_slug_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
