# Generated by Django 4.2.2 on 2023-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_moviecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
