# Generated by Django 4.2.2 on 2023-07-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_rating_movie_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='temp_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
