# Generated by Django 4.2.2 on 2023-07-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_temp_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.CharField(blank=True, null=True),
        ),
    ]
