# Generated by Django 4.2.2 on 2023-07-15 07:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_movie_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image URL'),
        ),
    ]
